### PR TITLE
Add svg disaster type icons

### PR DESCRIPTION
**Pull request by ghost**
Icons added and css disaster type colours adjusted to match. I'm unable to get the icons to display using `::before` pseudo elements for some reason; possibly due to bootstrap (I'm not familiar with it).

I'm happy to continue experimenting to try to get it working, but wanted to send a PR with the icons first.

### CODE REVIEW

**Comment by vincentsarago** [comment]
can you try that : 
http://stackoverflow.com/questions/19255296/is-there-a-way-to-use-svg-as-content-in-a-pseudo-element-before-or-after

```
.anchor:before
  display: block
  content: ' '
  background-image: url('../images/anchor.svg')
  background-size: 28px 28px
  height: 28px
  width: 28px
```

**Comment by vincentsarago** [comment]
@CodeMacabre 

both solution work: 

.fire:before {
  display: block;
  content: ' ';
  background-image: url('../img/fire.svg');
  background-size: 28px 28px;
  height: 28px;
  width: 28px;
}

.fire:before {
  display: inline-block;
  content: url('../img/fire.svg');
  height: 28px;
  width: 28px;
}

but have to adapt some codes

**Comment by ghost** [comment]
@vincentsarago How odd, I tried that but it didn't work for me. I probably missed something simple/obvious. Want me to add the code for each disaster type?

**Comment by vincentsarago** [comment]
@CodeMacabre no I'll do, but I have to figure out how to add them!

**Comment by ghost** [comment]
@vincentsarago Okay sure. If you want any more help or changes to the icons, let me know. I'm still not 100% about a couple of them (mainly tornado) so might make some tweaks. If you want to change colours, I'm happy to switch the icons to match.

**Pull request merged**
